targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scopes:
            - lib/graphql/**
          clients:
            - graphql
            - graphql_flutter
          scalars:
            ID:
#              type: String
              type: GithubNodeId
              fromJsonFunctionName: githubNodeIdFromJson
              toJsonFunctionName: githubNodeIdToJson
              import: package:repositoryviewer/type/github_node_id_type.dart
            URI:
              type: Uri
              fromJsonFunctionName: Uri.parse
            GitObjectID:
              type: String
            DateTime:
              type: DateTime
            Base64String:
              type: String
            Date:
              type: Datetime
            GitRefname:
              type: String
            JSON:
              type: Map<String, dynamic>