targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scopes:
            - lib/graphql/**
          clients:
            - graphql
            - graphql_flutter
          scalars:
            ID:
              type: GithubNodeID
              fromJsonFunctionName: githubNodeIDFromJson
              toJsonFunctionName: githubNodeIDToJson
              import: package:repositoryviewer/graphql/type/github_node_id_type.dart
            URI:
              type: Uri
              fromJsonFunctionName: uriFromJson
              toJsonFunctionName: uriToJson
              import: package:repositoryviewer/graphql/type/github_uri_type.dart