# frozen_string_literal: true

source "https://rubygems.org"


gem "fastlane", "2.206.2"
# Quick-fix for cocoapods issue on Apple Silicon.
# Based on: https://github.com/CocoaPods/CocoaPods/issues/10446#issuecomment-824157657
